Feature/Add eslint in the project and the components 1, 4
jlopezsa/ParkingApp-front-end pull request #17
Opened 2022-03-17 23:27 UTC by jlopezsa

## Descripción
Se adiciona las configuraciones de Eslint al proyecto.
Se crean los componenets 1(header) y 4(barra de busqueda)
A los archivos anteriores de instalar Eslint, se les adiciona la sentencia eslint-disable en la primera línea de código,

## Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [ ] 🤙 Solucion rapida
- [ ] 👌 Terminado y listo
- [x] 🤞 Espero que esto funcione, por favor revisar cuidadosamente

## Cómo probar?
### Instalar dependencias
`npm install`

### Inicias app
`npm start`

### Screenshots (si es aplicable)
[//]: <> (Capturas de pantalla que ayuden a entender que hiciste en este PR)

## Scope

- [ ] 🐞 Bugfix (non-breaking changes que resuelve un problema
- [ ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
- [x ] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
- [ ] ⚠️ Breaking change (cambio que no es compatible con versiones anteriores y/o cambia la funcionalidad actual)

2022-03-17 23:36 UTC, lmportoesq approved these changes

2022-03-17 23:45 UTC, lmportoesq approved these changes

2022-03-17 23:46 UTC, lmportoesq submitted a review, later dismissed

2022-03-18 15:09 UTC, buty619 requested changes
muchachos por fa validen las reglas que les esten afectando con eslint no tiene sentido que implementen eslint y después lo desactiven en un montón de archivos, porfa eliminen esas excepciones y si es necesario miramos caso por caso cual es el problema.

2022-03-18 15:09 UTC, buty619 commented on src/components/ParkingList/Parking/Parking.jsx
> +/* eslint-disable */
muchachos veo esta regla en un archivo no es buena idea tener una excepción de eslint en muchos lugares si les esta causando conflictos es preferible que cambien la regla, al final del dia eslint es una guia de buenas practicas pero eso no implica que no puedan cambiarlas de acuerdo a sus necesidades

2022-03-18 16:07 UTC, jlopezsa commented on src/components/ParkingList/Parking/Parking.jsx
> +/* eslint-disable */
Cristian, si es verdad, pero tomamos esa decisión porque ya teníamos muchos archivos y nos iba a tomar mucho tiempo arreglar el código. Decidimos adicionar la regla en los archivos viejos, y quitarla en los nuevos para no atrasarnos.
Nuestro inconveniente es como dar el paso para resolver los conflictos localmente

2022-03-18 17:46 UTC, buty619 commented on src/components/ParkingList/Parking/Parking.jsx
> +/* eslint-disable */
listo me queda super claro porfa no olvide de ir resolviendo de a pocos esos problemas de eslint, pero entiendo la razón gracias por la aclaración

2022-03-18 17:49 UTC, buty619 approved these changes

2022-03-18 17:50 UTC, merged