Feature/booking page
jlopezsa/ParkingApp-front-end pull request #28
Opened 2022-03-30 02:18 UTC by jlopezsa

## Descripción
Crea la página de reserva con informaciones como, resumen de la reserva y médios de pago

## Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [ ] 🤙 Solucion rapida
- [ ] 👌 Terminado y listo
- [ ] 🤞 Espero que esto funcione, por favor revisar cuidadosamente

[//]: <> ### Tickets
[//]: <> (El numero del ticket asociado a este PR)

## Cómo probar?
[//]: <> (Pasos necesarios para probar esta funcionalidad)

### Screenshots (si es aplicable)
[//]: <> (Capturas de pantalla que ayuden a entender que hiciste en este PR)

## Scope

- [ ] 🐞 Bugfix (non-breaking changes que resuelve un problema
- [ ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
- [ ] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
- [ ] ⚠️ Breaking change (cambio que no es compatible con versiones anteriores y/o cambia la funcionalidad actual)

2022-03-31 21:49 UTC, buty619 requested changes
pequeñas modificaciones¡

2022-03-31 21:49 UTC, buty619 commented on src/components/Header/Header.scss
> +    //background-image: url('../../figures/hamburguer_icon.svg');
elimina siempre los comments para que no pasen a producción

2022-03-31 21:49 UTC, buty619 commented on src/components/Menus/Menus.jsx
> +        <nav id="sidebar-menu">
creo que es mejor que muevan esto a su propio componente `NavBar`

2022-03-31 23:03 UTC, jlopezsa commented on src/components/Header/Header.scss
> +    //background-image: url('../../figures/hamburguer_icon.svg');
Para hacer estos cambios los puedo realizar en mi local y hacer nuevamenet `git push origin feature/booking-page` ?
O los realizo aquí en GitHub directamente?

2022-03-31 23:05 UTC, lmportoesq approved these changes, later dismissed
Well done Julian...

2022-04-02 14:46 UTC, jlopezsa commented on src/components/Menus/Menus.jsx
> +        <nav id="sidebar-menu">
Perfecto, ya cree un componente NavBar que contiene el menu horizontal y desplegable. 
Voy a subir los cambios en esta misma rama

2022-04-02 14:51 UTC, jlopezsa commented on src/components/Header/Header.scss
> +    //background-image: url('../../figures/hamburguer_icon.svg');
Ya se borraron los comentários

2022-04-04 16:33 UTC, buty619 approved these changes

2022-04-04 19:20 UTC, merged